### ISSUE TITLE
Question about an URGNA2012 / URDNA2015 algorithm change

### ISSUE THREAD

**Issue by danpape** [json-ld/normalization#18]
Hi - I have some code that implements the URGNA2012 algorithm that I'm trying to "upgrade" to URDNA2015. 

The first bullet point in Appendix A, https://json-ld.github.io/normalization/spec/index.html#urgna2012 states "... if any blank node was used in the graph name position in the quad, then the value was serialized using the special blank node identifier _:g, instead of _:z." However, in the description for the URDNA2015 algorithm for "Hash First Degree Quads", https://json-ld.github.io/normalization/spec/index.html#algorithm-1 parts 3.1.1 and 3.1.1.1 imply the blank node identifiers should be replaced with _:a or _:z for all components in the quad, including the graph name.

I'm wondering if the first bullet point in Appendix A should be changed to say "... blank node identifier _:g, instead of _:a or _:z, as described in the algorithm for "Hash First Degree Quads"." or something like that.

Or... should the graph name in "Hash First Degree Quads" really always be replaced with _:z regardless of whether it matches the reference blank node identifier?

**Comment by dlongley** [comment]
> I'm wondering if the first bullet point in Appendix A should be changed to say "... blank node identifier _:g, instead of _:a or _:z, as described in the algorithm for "Hash First Degree Quads"." or something like that.

Yes, the URGNA2012 text should be changed to that. Sorry for the confusion!

> Or... should the graph name in "Hash First Degree Quads" really always be replaced with _:z regardless of whether it matches the reference blank node identifier?

No, it should use `_:a` or `_:z` based on whether the identifier matches the reference one (the URDNA2015 spec text is correct).

**Comment by danpape** [comment]
OK, that's what I was hoping. Thanks for clearing that up for me.
